### ISSUE TITLE
InView event not triggered when a parent element is in an animation.

### ISSUE THREAD

**Issue by SNiels** [thenikso/angular-inview#67]
First off, great plugin!
I use the in-view event to animate in elements the moment they enter the viewport.
Now that I've added routing animations, they only appear after scrolling.
```css
/* Default view */
.view{
  width: 100%;
  transition: 300ms;
}
/* First animation*/
.resumeAnimation .view.ng-enter{
  transform: translateX(-100%);
}
.resumeAnimation .view.ng-enter.ng-enter-active{
  transform: translateX(0%);
}
.resumeAnimation .view.ng-leave{
  transform: translateX(0%);
}
.resumeAnimation .view.ng-leave.ng-leave-active{
  transform: translateX(100%);
}
/* Second animation*/
.projectsAnimation .view.ng-enter{
  transform: translateX(100%);
}
.projectsAnimation .view.ng-enter.ng-enter-active{
  transform: translateX(0%);
}
.projectsAnimation .view.ng-leave{
  transform: translateX(0%);
}
.projectsAnimation .view.ng-leave.ng-leave-active{
  transform: translateX(-100%);
}
```
I have a small workaround, I force the browser to scroll at least 2 pixels when the user changes route. Though, I don't really like this workaround. Is there a way for to force the elements to check if they are visible? So I can call that after the animation has been run?
```js
$rootScope.$on('$routeChangeStart', function(event, currRoute, prevRoute){
		    $rootScope.animation = currRoute.animation;
            if($document.scrollTop()==0){
                $document.scrollTo(0,2,800);
            }else{
                $document.scrollTo(0,0,800);
            }
	  });
```

You can find out the project at https://github.com/SNiels/portfolio
